"use client";

import { useDeferredValue, useEffect, useMemo, useRef, useState, type ChangeEvent, type DragEvent } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FEATURE_NAMES, SNAPSHOT, parseFeatures, summarize, filterRecords, exportFeatures, saveCSV, HEADER_ONLY_TEMPLATE, type FeatureRecord } from "../lib/features";

const sections = [{id:"overview",name:"Overview"},{id:"explorer",name:"Student explorer"},{id:"method",name:"The approach"},{id:"paper",name:"Research paper"}];
const descriptions = ["Showing up for pseudocode sessions.","Understanding concepts before implementation.","Turning practice into completed problems.","Applying knowledge in coding assessments.","Participation in coding assessments.","Maintaining a steady learning rhythm."];
const fmt = (n:number) => n.toLocaleString("en-US");
function sampleRecords():FeatureRecord[] {
 return Array.from({length:12},(_,i)=>({id:`DEMO${String(i+1).padStart(3,"0")}`,name:`Sample learner ${String(i+1).padStart(2,"0")}`,roll:`DEMO-${101+i}`,values:[78,68,61,74,85,70].map((v,j)=>Math.max(5,Math.min(100,v+((i*17+j*7)%31)-15-(i%4===0?32:0)))),problems:12+i*4,inactive:i%4===0?3:0,tier:i%3===0?"Developing":"Progressing",category:i%4===0?"Disengaged":"Normal",severity:i%4===0?"Review":"None",label:i%4===0}));
}

export function LearningObservatory() {
 const [records,setRecords]=useState<FeatureRecord[]>([]);
 const [source,setSource]=useState<"snapshot"|"demo"|"csv">("snapshot");
 const [fileName,setFileName]=useState("");
 const [busy,setBusy]=useState(false);
 const [status,setStatus]=useState("");
 const [error,setError]=useState(false);
 const [query,setQuery]=useState("");
 const [tier,setTier]=useState("All tiers");
 const [category,setCategory]=useState("All labels");
 const [flagged,setFlagged]=useState(false);
 const [feature,setFeature]=useState(3);
 const [minimum,setMinimum]=useState(0);
 const [sort,setSort]=useState("id");
 const [page,setPage]=useState(0);
 const [chart,setChart]=useState("profile");
 const [selected,setSelected]=useState<FeatureRecord|null>(null);
 const [policy,setPolicy]=useState("");
 const [motion,setMotion]=useState(true);
 const [active,setActive]=useState("overview");
 const [menu,setMenu]=useState(false);
 const [dragging,setDragging]=useState(false);
 const input=useRef<HTMLInputElement>(null), search=useRef<HTMLInputElement>(null), dialog=useRef<HTMLDialogElement>(null), root=useRef<HTMLDivElement>(null);
 const deferredQuery=useDeferredValue(query);
 const loaded=records.length>0;
 const reset=()=>{setQuery("");setTier("All tiers");setCategory("All labels");setFlagged(false);setMinimum(0);setPage(0);};
 const filtered=useMemo(()=>filterRecords(records,deferredQuery,tier,category,flagged,feature,minimum).sort((a,b)=>sort==="score"?b.values[feature]-a.values[feature]:a.id.localeCompare(b.id)),[records,deferredQuery,tier,category,flagged,feature,minimum,sort]);
 const totals=loaded?summarize(records):SNAPSHOT;
 const summary=loaded?summarize(filtered):SNAPSHOT;
 const tiers=useMemo(()=>Array.from(new Set(records.map(r=>r.tier))),[records]);
 const categories=useMemo(()=>Array.from(new Set(records.map(r=>r.category))),[records]);
 const sourceTitle=source==="csv"?fileName:source==="demo"?"Interactive sample":"Reference snapshot";
 const bars=useMemo(()=>chart==="profile"?FEATURE_NAMES.map((name,i)=>({name,value:Number(summary.averages[i].toFixed(1))})):chart==="labels"?(loaded?Array.from(new Set(filtered.filter(r=>r.label===true).map(r=>r.category))).map(name=>({name,value:filtered.filter(r=>r.label===true&&r.category===name).length})):SNAPSHOT.labels.map(r=>({name:r.name,value:r.count}))):Array.from({length:10},(_,i)=>({name:`${i*10}–${i*10+10}`,value:filtered.filter(r=>r.values[feature]>=i*10&&(i===9?r.values[feature]<=100:r.values[feature]<i*10+10)).length})),[chart,summary,filtered,loaded,feature]);

 useEffect(()=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)");const update=()=>setMotion(!media.matches);update();media.addEventListener("change",update);return ()=>media.removeEventListener("change",update);},[]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target);}}),{threshold:.08});root.current?.querySelectorAll(".reveal").forEach(el=>observer.observe(el));return ()=>observer.disconnect();},[]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)setActive(entry.target.id);}),{rootMargin:"-15% 0px -55% 0px"});sections.forEach(s=>{const el=document.getElementById(s.id);if(el)observer.observe(el);});return ()=>observer.disconnect();},[]);
 useEffect(()=>{if(selected||policy)dialog.current?.showModal();else dialog.current?.close();},[selected,policy]);
 useEffect(()=>setPage(0),[deferredQuery,tier,category,flagged,feature,minimum,sort,records]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.getElementById("explorer")?.scrollIntoView({behavior:motion?"smooth":"instant"});search.current?.focus({preventScroll:true});}};window.addEventListener("keydown",key);return ()=>window.removeEventListener("keydown",key);},[motion]);
 const openImport=()=>input.current?.click();
 const closeDialog=()=>{setSelected(null);setPolicy("");};
 const go=(id:string)=>{setActive(id);setMenu(false);};
 async function importFile(file:File) {
  if(busy)return;
  setBusy(true);setStatus("");setError(false);
  try {
   if(file.size>2_000_000)throw Error("Choose a CSV smaller than 2 MB.");
   const parsed=parseFeatures(await file.text());
   setRecords(parsed);setSource("csv");setFileName(file.name);reset();
   setStatus(`Imported ${fmt(parsed.length)} students. Your data stays in this browser tab.`);
  }catch(e){setError(true);setStatus(e instanceof Error?e.message:"Could not read this file.");}
  finally{setBusy(false);}
 }
 function importChange(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(f)void importFile(f);e.target.value="";}
 function drop(e:DragEvent){e.preventDefault();setDragging(false);const f=e.dataTransfer.files?.[0];if(f)void importFile(f);}
 function loadDemo(){reset();setRecords(sampleRecords());setSource("demo");setStatus("Sample data loaded. These 12 fictional learners are for trying the interface only.");setError(false);document.getElementById("explorer")?.scrollIntoView({behavior:motion?"smooth":"instant"});}

 return <div className={`studio ${motion?"":"motion-off"}`} ref={root}>
  <a className="skip-link" href="#explorer">Skip to student explorer</a>
  <aside className={`sidebar ${menu?"menu-open":""}`}>
   <a href="#overview" className="brand" onClick={()=>go("overview")}><span className="brand-mark" aria-hidden="true">e.</span><span>edusentiel<small>LEARNING RESEARCH STUDIO</small></span></a>
   <button className="mobile-menu" onClick={()=>setMenu(v=>!v)} aria-expanded={menu} aria-controls="studio-navigation">{menu?"Close":"Menu"}</button>
   <div className="sidebar-body"><span className="rail-label">THE WORKSPACE</span><nav id="studio-navigation" aria-label="Main navigation">{sections.map((s,i)=><a key={s.id} href={`#${s.id}`} className={active===s.id?"active":""} aria-current={active===s.id?"location":undefined} onClick={()=>go(s.id)}><span className="nav-number">0{i+1}</span>{s.name}</a>)}</nav>
   <div className="rail-note"><span className="rail-label">A NOTE ON THE WORK</span><p>Behind every learning pattern is a person worth understanding.</p><a href="#method" onClick={()=>go("method")}>Read our approach</a></div>
   <div className="rail-bottom"><span>RESEARCH EDITION / 2026</span><button onClick={()=>setMotion(v=>!v)} aria-pressed={!motion}>{motion?"Motion on":"Motion paused"}</button><a href="https://github.com/ishuu9837/edusentinel" target="_blank" rel="noopener noreferrer">View source</a></div></div>
  </aside>
  <input ref={input} type="file" accept=".csv,text/csv" onChange={importChange} hidden aria-label="Import student CSV"/>
  <main className="studio-main">
   <section id="overview" className="overview">
    <div className="folio"><span>01 / THE OBSERVATORY</span><span className="folio-right">STUDENT PATTERNS, HUMAN CONTEXT</span></div>
    <div className="intro"><div className="intro-copy"><div className="eyebrow">A clearer view of how students learn</div><h1>Learning behaviour,<br/><em>in focus.</em></h1><p>Make sense of participation, practice, and progress. An open research workspace for noticing the patterns that deserve a closer look.</p><div className="hero-actions"><button className="button primary" onClick={openImport} disabled={busy}>{busy?"Reading CSV…":"Import your dataset"}</button><button className="text-button" onClick={loadDemo}>Try the interactive sample</button></div><div className="hero-caption">Six learning signals. One thoughtful conversation.</div></div>
    <div className="signal-sheet"><div className="sheet-top"><span>FIELD NOTES / 001</span><span>THE LEARNING PROFILE</span></div><div className="sheet-title">A pattern is a<br/><em>starting point.</em></div><div className="signal-list" aria-label="Reference cohort feature averages">{FEATURE_NAMES.map((name,i)=><div className="signal-row" key={name}><span className="signal-num">0{i+1}</span><div><span>{name}</span><div className="signal-track"><span style={{width:totals.averages[i]+"%"}}/></div></div><strong>{totals.averages[i].toFixed(0)}<small>%</small></strong></div>)}</div><div className="sheet-caption">{loaded?"Means from the active cohort":"Means from the supplied file snapshot"}<span>Explore below</span></div></div></div>
    <div className="cohort-strip"><div><span>COHORT SIZE</span><strong>{fmt(totals.count)}<small>students</small></strong></div><div><span>SUPPLIED ANOMALY LABELS</span><strong>{fmt(totals.flagged)}<small>for contextual review</small></strong></div><div className="strip-note"><span>WHAT YOU ARE SEEING</span><p>{source==="csv"?"Your imported learning metrics and supplied labels.":source==="demo"?"Fictional sample records. Import your CSV to work with your students.":"A reference snapshot of 1,019 records. Import the file to explore individual students."}</p></div></div>
   </section>

   <section id="explorer" className="explorer section-block reveal">
    <div className="section-heading"><div><div className="eyebrow">02 / THE WORKING EXPLORER</div><h2>Find the story<br/><em>inside the data.</em></h2></div><div className="heading-aside"><span className={`source-status ${source==="demo"?"sample":""}`}>{sourceTitle}</span><p>{source==="demo"?"Fictional records / not model predictions":source==="csv"?"Imported locally / labels supplied by your file":"Aggregate view / import to search students"}</p></div></div>
    <div className={`import-line ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();if(!busy)setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={drop}><div><span className="import-marker" aria-hidden="true">CSV</span><div><strong>{loaded?"Bring in a different cohort":"Bring your students into focus"}</strong><p>Drop features_df.csv here, or select your file. No column conversion needed.</p></div></div><div className="import-links"><button className="text-button" onClick={openImport} disabled={busy}>{busy?"Reading…":"Choose CSV"}</button><button className="text-button subdued" onClick={()=>saveCSV("edusentiel-template.csv",HEADER_ONLY_TEMPLATE)}>Get template</button></div></div>
    {status&&<div role={error?"alert":"status"} className={`notice ${error?"error":""}`}><span>{status}</span><button aria-label="Dismiss message" onClick={()=>setStatus("")}>Close</button></div>}
    <div className="search-line"><label htmlFor="student-search">SEARCH YOUR COHORT</label><div className="search-box"><span aria-hidden="true" className="search-symbol"/><input ref={search} id="student-search" type="search" placeholder="Search by name, roll number, or student ID" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><span className="search-hint">{loaded?`${fmt(filtered.length)} of ${fmt(records.length)} students`:"Import your CSV or open the sample to activate results."}</span></div>
    <div className="filter-line"><label>Tier<select value={tier} onChange={e=>setTier(e.target.value)} disabled={!loaded}><option>All tiers</option>{tiers.map(t=><option key={t}>{t}</option>)}</select></label><label>Dataset label<select value={category} onChange={e=>setCategory(e.target.value)} disabled={!loaded}><option>All labels</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={flagged} onChange={e=>setFlagged(e.target.checked)} disabled={!loaded}/>Anomaly-labelled only</label><button className="text-button reset" onClick={reset} disabled={!loaded}>Reset filters</button></div>
    <div className="chart-layout"><div className="chart-controls"><div className="eyebrow">THE SIGNALS</div><h3>A closer look.</h3><p>Compare the learning profile or focus on a single metric. The charts follow your student filters.</p><label>Feature in focus<select value={feature} onChange={e=>setFeature(Number(e.target.value))}>{FEATURE_NAMES.map((n,i)=><option key={n} value={i}>{n}</option>)}</select></label><label className="range-label">Minimum value <output>{minimum}%</output><input type="range" min="0" max="100" value={minimum} onChange={e=>setMinimum(Number(e.target.value))} disabled={!loaded}/></label><p className="fine-note">Supplied labels describe the dataset. This interface does not run the trained model.</p></div><div className="chart-surface"><div className="chart-heading"><h3>{chart==="profile"?"Cohort profile":chart==="labels"?"Label breakdown":FEATURE_NAMES[feature]}</h3><span>{chart==="profile"?"MEAN / 0–100%":"STUDENT COUNT"}</span></div><div className="chart-tabs" role="group" aria-label="Chart views">{[["profile","Profile"],["labels","Labels"],["distribution","Distribution"]].map(([id,name])=><button key={id} aria-pressed={chart===id} onClick={()=>setChart(id)} disabled={id==="distribution"&&!loaded}>{name}</button>)}</div>{busy?<div className="chart-skeleton" role="status" aria-label="Reading dataset">{Array.from({length:6},(_,i)=><span key={i}/>)}</div>:<div className="chart-scroll"><div className="chart-canvas"><ResponsiveContainer width="100%" height={250}><BarChart data={bars} margin={{top:18,left:-23,right:6,bottom:10}}><CartesianGrid vertical={false} stroke="#d7d1c5" strokeDasharray="3 5"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:"#5c625f",fontSize:10}} interval={0} tickFormatter={v=>chart==="profile"?String(v).replace("Pseudocode","Pseudo.").replace("attendance","attend.").replace("completion","comp.").replace("consistency","consist."):String(v)}/><YAxis domain={chart==="profile"?[0,100]:[0,"auto"]} axisLine={false} tickLine={false} tick={{fill:"#747976",fontSize:11}}/><Tooltip cursor={false} contentStyle={{background:"#eeeadf",border:"1px solid #c9c4b8",borderRadius:0,boxShadow:"none",color:"#273438",fontSize:13}} formatter={v=>[v,chart==="profile"?"Average (%)":"Students"]}/><Bar dataKey="value" fill="#9c753b" maxBarSize={40} isAnimationActive={motion} animationDuration={550} animationEasing="ease-out"/></BarChart></ResponsiveContainer></div></div>}<div className="chart-foot"><span>{loaded?`${fmt(filtered.length)} matching students`:"Reference file aggregates"}</span><span>{chart==="profile"?"Higher values indicate more of the measured signal.":"Counts reflect the current view."}</span></div></div></div>
    <div className="register"><div className="register-top"><h3>The student register <span>{loaded?fmt(filtered.length):"00"}</span></h3><div><select aria-label="Sort students" value={sort} onChange={e=>setSort(e.target.value)} disabled={!loaded}><option value="id">Student ID</option><option value="score">Highest feature value</option></select><button className="button secondary compact" disabled={!loaded||!filtered.length} onClick={()=>saveCSV("edusentiel-filtered-students.csv",exportFeatures(filtered))}>Export view</button></div></div>{!loaded?<div className="empty-state"><span className="empty-index">YOUR COHORT / YOUR CONTEXT</span><h3>Every row has a story.</h3><p>Import your CSV to search and inspect individual students.<br/>Or explore twelve fictional records to try the workspace.</p><div><button className="button primary" onClick={openImport}>Import dataset</button><button className="text-button" onClick={loadDemo}>Open sample data</button></div></div>:<><div className="table-scroll"><table><thead><tr><th>STUDENT / ROLL</th><th>{FEATURE_NAMES[feature].toUpperCase()}</th><th>PROBLEMS</th><th>INACTIVE WEEKS</th><th>DATASET LABEL</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{filtered.slice(page*8,page*8+8).map(r=><tr key={r.id}><td><strong>{r.name||r.id}</strong><span>{r.roll||r.id}</span></td><td><div className="score-cell"><span>{r.values[feature].toFixed(1)}%</span><div><i style={{width:`${r.values[feature]}%`}}/></div></div></td><td>{r.problems??"Unavailable"}</td><td>{r.inactive??"Unavailable"}</td><td><span className={`label-tag ${r.label?"attention":""}`}>{r.category}</span></td><td><button className="text-button" onClick={()=>setSelected(r)} aria-label={`Inspect ${r.name||r.id}`}>Inspect</button></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="no-results"><h3>No matching students.</h3><p>Try a different name or roll number, or clear your filters.</p><button className="text-button" onClick={reset}>Clear filters</button></div>}<div className="pagination"><span>{filtered.length?Math.min(page*8+1,filtered.length):0}–{Math.min(page*8+8,filtered.length)} / {fmt(filtered.length)} students</span><div><button onClick={()=>setPage(p=>p-1)} disabled={page===0}>Previous</button><button onClick={()=>setPage(p=>p+1)} disabled={(page+1)*8>=filtered.length}>Next</button></div></div></>}</div>
   </section>

   <section id="method" className="method section-block reveal"><div className="eyebrow">03 / THE APPROACH</div><div className="method-layout"><div><h2>Notice a pattern.<br/><em>Start a conversation.</em></h2><p className="section-description">Attendance, practice, scores, and consistency offer different views of learning. Put them together, then bring the student's own context into the conversation.</p></div><div className="method-rows">{[["01","Observe","Read six learning metrics together. Look for patterns in participation, practice, assessment, and consistency."],["02","Understand","A sudden change may reflect course demands, access difficulties, or a different study rhythm. A label alone cannot explain why."],["03","Support","Review the learning context with the student. Use the evidence to guide a useful conversation and appropriate support."]].map(([n,title,body])=><details key={n} open={n==="01"}><summary><span>{n}</span>{title}<b aria-hidden="true">+</b></summary><p>{body}</p></details>)}</div></div><div className="method-note"><span>ABOUT THE MODEL</span><p>The research studies autoencoder-based anomaly detection. This web workspace reads the labels supplied in your CSV. It does not train or run the pickle model.</p></div></section>

   <section id="paper" className="paper section-block reveal"><div className="eyebrow">04 / THE RESEARCH</div><div className="paper-layout"><div className="paper-object" aria-hidden="true"><div>EDUSENTIEL / RESEARCH</div><span className="paper-rule"/><p>Abnormal<br/>Learning<br/><em>Behaviour.</em></p><span className="paper-edition">THE PROJECT PAPER<br/>PDF / RESEARCH EDITION</span></div><div className="paper-copy"><span className="eyebrow">READ BEYOND THE INTERFACE</span><h2>The thinking<br/><em>behind the signals.</em></h2><p>Read the project paper for the research behind abnormal learning behaviour detection, its methodology, and the context for interpreting results.</p><div className="paper-actions"><a className="button primary" href="/api/paper" download="Edusentiel-Research-Paper.pdf">Download the paper</a><a className="text-button" href="/paper" target="_blank" rel="noopener noreferrer">Read online</a></div><span className="paper-format">PDF DOCUMENT / ORIGINAL PROJECT PAPER</span></div></div></section>
   <footer className="footer"><div><span className="footer-brand">edusentiel.</span><p>Learning patterns. Human context.</p></div><div><button onClick={()=>setPolicy("Privacy Policy")}>Privacy</button><button onClick={()=>setPolicy("Terms of Service")}>Terms</button><a href="#overview" onClick={()=>go("overview")}>Back to top</a></div><span>RESEARCH WORKSPACE / 2026</span></footer>
  </main>
  <dialog ref={dialog} className="detail-dialog" aria-labelledby="dialog-title" onCancel={closeDialog} onClose={closeDialog}><div className="dialog-top"><span>{selected?"STUDENT CONTEXT":"WORKSPACE POLICY"}</span><button className="text-button" onClick={closeDialog}>Close</button></div>{selected?<><h2 id="dialog-title">{selected.name||selected.id}</h2><p className="detail-identity">{selected.id} / Roll: {selected.roll||"Not supplied"}</p><div className="detail-label"><span className={`label-tag ${selected.label?"attention":""}`}>{selected.category}</span><span>{selected.tier}</span></div><div className="detail-signals">{FEATURE_NAMES.map((n,i)=><div key={n}><span>{n}</span><strong>{selected.values[i].toFixed(1)}%</strong><div><i style={{width:`${selected.values[i]}%`}}/></div></div>)}</div><div className="detail-meta"><div>Problems solved<strong>{selected.problems??"Not supplied"}</strong></div><div>Inactive weeks<strong>{selected.inactive??"Not supplied"}</strong></div></div><p className="fine-note">{source==="demo"?"Fictional sample record. ":""}The label is supplied by the dataset, not predicted by this interface. Interpret these values alongside the student's course and access needs.</p></>:<><h2 id="dialog-title">{policy}</h2>{policy==="Privacy Policy"?<><p>CSV files are parsed in memory within your browser tab. This interface does not transmit the imported rows, save them in browser storage, or create a student account.</p><p>Names and roll numbers are retained temporarily for search. Emails and candidate IDs are discarded. Exports omit names and roll numbers. Reloading the page clears imported data.</p><p>The optional sample contains fictional learners. The default snapshot contains aggregate values only. Hosting providers may process ordinary connection data under their own policies.</p></>:<><p>This is a research workspace for exploring learning metrics and annotations supplied in a CSV. It does not run the trained model or establish academic misconduct, diagnosis, or learning ability.</p><p>Use only data you have permission to process. Review results in context and avoid relying on a label alone for consequential decisions.</p><p>The workspace has no payment or account service and no production availability commitment.</p></>}</>}</dialog>
 </div>;
}
