"use client";
import React, { useMemo, useState, useRef, useEffect } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";

import { SAMPLE, CSV_HEADER, parseCSV, download, esc, type Student } from "../lib/cohort";
export const LearningObservatory = () => {
 const [students,setStudents]=useState<Student[]>(SAMPLE),[source,setSource]=useState("Synthetic demonstration"),[view,setView]=useState("Observatory"),[threshold,setThreshold]=useState(.065),[query,setQuery]=useState(""),[course,setCourse]=useState("All courses"),[onlyFlagged,setOnlyFlagged]=useState(false),[selected,setSelected]=useState<Student|null>(null),[policy,setPolicy]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[sort,setSort]=useState("error"),[page,setPage]=useState(0);
 const fileRef=useRef<HTMLInputElement>(null),dialogRef=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(selected||policy)dialogRef.current?.showModal();else dialogRef.current?.close();},[selected,policy]);
 useEffect(()=>{setPage(0);},[query,course,onlyFlagged,students,sort,threshold]);
 const flagged=students.filter(s=>s.error>threshold),courses=Array.from(new Set(students.map(s=>s.course)));
 const filtered=useMemo(()=>students.filter(s=>(course==="All courses"||s.course===course)&&s.id.toLowerCase().includes(query.toLowerCase())&&(!onlyFlagged||s.error>threshold)).sort((a,b)=>sort==="error"?b.error-a.error:a.id.localeCompare(b.id)),[students,query,course,onlyFlagged,threshold,sort]);
 const maxError=Math.max(.15,...students.map(s=>s.error))*1.001;
 const histogram=Array.from({length:15},(_,i)=>{const lo=i*maxError/15,hi=(i+1)*maxError/15;return {label:lo.toFixed(3),mid:(lo+hi)/2,within:students.filter(s=>s.error>=lo&&s.error<hi&&s.error<=threshold).length,review:students.filter(s=>s.error>=lo&&s.error<hi&&s.error>threshold).length};});
 async function importFile(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setBusy(true);setMessage("");try{if(file.size>2_000_000)throw Error("Choose a CSV smaller than 2 MB.");const text=await file.text();const parsed=parseCSV(text);if(parsed.length>10000)throw Error("Use up to 10,000 rows.");setStudents(parsed);setSource(file.name);setCourse("All courses");setMessage("Imported "+parsed.length+" records. Data stays in this browser tab.");}catch(e){setMessage(e instanceof Error?e.message:"Could not read this file.");}finally{setBusy(false);event.target.value="";}}
 function exportRows(){download("edusentiel-review.csv",CSV_HEADER+",review_status\n"+filtered.map(s=>[s.id,s.course,s.sessions,s.minutes,s.completion,s.error,s.error>threshold?"Review":"Within threshold"].map(esc).join(",")).join("\n"));setMessage("Exported "+filtered.length+" records at threshold "+threshold.toFixed(3)+".");}
 return <div className="edu min-h-screen">

 <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setView("Observatory");}}><span className="monogram">e.</span><span>edusentiel<span className="brand-small">LEARNING INTELLIGENCE</span></span></a>
 <div className="workspace-label">RESEARCH WORKSPACE <span>01</span></div>
 <nav aria-label="Main navigation">{["Observatory","Student register","Method & model"].map((v,i)=><button key={v} className={view===v?"nav-item active":"nav-item"} onClick={()=>setView(v)}><span className="nav-number">0{i+1}</span>{v}</button>)}</nav>
 <div className="sidebar-note"><span className="tiny">THE HUMAN CONTEXT</span><p>A signal starts a conversation.</p><span className="muted-note">Review learning patterns with care. A model score never defines a student.</span></div>
 <div className="sidebar-bottom"><div className="workspace-avatar">ER</div><div>Education research<span className="brand-small">LOCAL DEMO WORKSPACE</span></div></div>
 </aside>
 <div className="main"><header className="topbar"><span>Workspace <span className="slash">/</span> {view}</span><span className="demo-label">BROWSER-LOCAL DEMO</span></header>
 <main><div className="page-heading"><div><div className="eyebrow">EDUSENTIEL / RESEARCH SERIES 001</div><h1>{view==="Observatory"?"The learning observatory.":view==="Student register"?"Every student, in context.":"Understand the signal."}</h1><p className="subtitle">{view==="Method & model"?"A transparent view of what this demonstration can tell you.":"Find the patterns that deserve a closer look."}</p></div><button className="primary" onClick={()=>fileRef.current?.click()} disabled={busy}>{busy?"Reading CSV…":"Import cohort CSV"}</button><input type="file" accept=".csv,text/csv" hidden ref={fileRef} onChange={importFile}/></div>
 <div className="dataset-line"><span className="dataset-tag">DATA SOURCE</span><span>{source}</span><button className="text-button" onClick={()=>download("edusentiel-template.csv",CSV_HEADER+"\nED-1001,Biotechnology,12,36,78,0.042\nED-1002,Biotechnology,5,18,42,0.092")}>Download CSV template</button>{source!=="Synthetic demonstration"&&<button className="text-button" onClick={()=>{setStudents(SAMPLE);setSource("Synthetic demonstration");setCourse("All courses");setMessage("Synthetic demonstration restored.");}}>Reset demo</button>}</div>
 {message&&<p className="notice" role="status">{message}<button aria-label="Dismiss message" onClick={()=>setMessage("")}>Close</button></p>}
 {view==="Method & model"?<section className="method"><div className="method-index">01 / MODEL NOTES</div><h2>Reconstruction error is a starting point.</h2><p>An autoencoder learns to reconstruct familiar input patterns. Larger differences between the input and reconstruction may indicate unusual behaviour. Those differences require human interpretation.</p><div className="method-rule"><h3>What this demo does</h3><p>Reads reconstruction errors already present in your CSV. Compares each score with your chosen threshold. Displays distributions and creates a review queue.</p></div><div className="method-rule"><h3>What still needs validation</h3><p>Your notebook and model were unavailable for inspection. No model inference, accuracy, ROC score, or confusion matrix is claimed here. The supplied demonstration rows are synthetic.</p></div><div className="method-rule"><h3>Interpret with context</h3><p>Course structure, accessibility needs, connectivity, and study habits can affect learning activity. Speak with the student before drawing conclusions. Do not use this demo for grading or disciplinary decisions.</p></div><div className="method-rule"><h3>CSV contract</h3><p>Student ID, course, sessions, average minutes, completion percentage, and reconstruction error. Sessions must be a nonnegative integer, completion must be 0 to 100, and all other numerical values must be nonnegative. Use pseudonymous IDs.</p></div></section>:<>
 {view==="Observatory"&&<><section className="summary" aria-label="Cohort summary"><div className="summary-primary"><div className="tiny">COHORT IN FOCUS</div><div className="metric">{students.length.toLocaleString()}<span>students</span></div><p>{courses.length} courses represented in this dataset</p></div><div className="summary-secondary"><div className="tiny">ABOVE YOUR THRESHOLD</div><div className="metric rust">{flagged.length.toLocaleString()}<span>for review</span></div><p>{(flagged.length/students.length*100).toFixed(1)}% of the cohort • requires human context</p></div><div className="summary-annotation"><span className="index">/01</span><p>Observe.<br/>Understand.<br/><em>Support.</em></p></div></section>
 <section className="distribution"><div className="section-top"><div><div className="eyebrow">PATTERN DISTRIBUTION</div><h2>Where the cohort sits</h2></div><div className="legend"><span className="legend-green"/> Within threshold <span className="legend-rust"/> Above threshold</div></div><div className="chart-and-control"><div className="chart-area">{busy?<div className="skeleton" aria-label="Loading dataset"/>:<ResponsiveContainer width="100%" height={230}><BarChart data={histogram} margin={{top:20,right:12,bottom:10,left:-20}}><XAxis dataKey="label" tickLine={false} axisLine={{stroke:"#bfb9aa"}} tick={{fontSize:10,fill:"#6d746d"}} interval={2}/><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{fontSize:10,fill:"#6d746d"}}/><Tooltip cursor={false} contentStyle={{background:"#eee9dd",border:"1px solid #bfb9aa",borderRadius:0,boxShadow:"none"}} formatter={(value,name)=>[value,name]} labelFormatter={label=>"Error bin starts at "+label}/><Bar dataKey="within" name="Within threshold" stackId="scores" fill="#244b3b" isAnimationActive={false}/><Bar dataKey="review" name="Above threshold" stackId="scores" fill="#9b492e" isAnimationActive={false}/></BarChart></ResponsiveContainer>}<div className="axis-caption">RECONSTRUCTION ERROR</div></div><div className="threshold-panel"><div className="tiny">REVIEW THRESHOLD</div><output className="threshold-value" htmlFor="threshold">{threshold.toFixed(3)}</output><input id="threshold" aria-label="Review threshold" type="range" min="0" max={Math.max(.15,maxError).toFixed(3)} step=".001" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/><div className="range-labels"><span>0.000</span><span>{Math.max(.15,maxError).toFixed(3)}</span></div><p>Scores above this value enter the review queue.</p><button className="text-button" onClick={()=>{setOnlyFlagged(true);document.getElementById("register")?.scrollIntoView({behavior:"auto"});}}>View {flagged.length} flagged students</button></div></div><div className="chart-footnote">Bins group nearby scores; classification uses each exact score. The threshold is exploratory.</div></section></>}
 <section className="register" id="register"><div className="section-top"><div><div className="eyebrow">THE STUDENT REGISTER</div><h2>{onlyFlagged?"Ready for a closer look":"Patterns, with people behind them"}</h2></div><button className="outline" onClick={exportRows}>Export current view</button></div>
 <div className="filters"><input aria-label="Search student ID" placeholder="Search student ID" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter course" value={course} onChange={e=>setCourse(e.target.value)}><option>All courses</option>{courses.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Sort records" value={sort} onChange={e=>setSort(e.target.value)}><option value="error">Highest error first</option><option value="id">Student ID</option></select><label className="filter-checkbox"><input type="checkbox" checked={onlyFlagged} onChange={e=>setOnlyFlagged(e.target.checked)}/>Review queue only</label></div>
 <div className="table-wrap"><table><thead><tr><th>STUDENT / COURSE</th><th>SESSIONS</th><th>AVG. MINUTES</th><th>COMPLETION</th><th>RECON. ERROR</th><th>STATUS</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{filtered.slice(page*8,page*8+8).map(s=><tr key={s.id}><td><strong>{s.id}</strong><span className="course-name">{s.course}</span></td><td>{s.sessions}</td><td>{s.minutes.toFixed(1)}</td><td><div className="completion"><span>{s.completion.toFixed(0)}%</span><span className="track"><span style={{width:s.completion+"%"}}/></span></div></td><td className="numeric">{s.error.toFixed(3)}</td><td><span className={s.error>threshold?"status review":"status"}>{s.error>threshold?"Review":"Within threshold"}</span></td><td><button className="text-button" onClick={()=>setSelected(s)} aria-label={"Open details for "+s.id}>Details</button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty"><h3>No students match these filters.</h3><button className="outline" onClick={()=>{setQuery("");setCourse("All courses");setOnlyFlagged(false);}}>Clear filters</button></div>}</div>
 <div className="table-bottom"><span>{filtered.length?Math.min(page*8+1,filtered.length):0}–{Math.min(page*8+8,filtered.length)} of {filtered.length} records</span><div><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={(page+1)*8>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></section></>}
 <footer><span>EDUSENTIEL <span className="footer-divider">/</span> Learning deserves context.</span><div><button onClick={()=>setPolicy("Privacy Policy")}>Privacy Policy</button><button onClick={()=>setPolicy("Terms of Service")}>Terms of Service</button></div></footer>
 </main></div>
 <dialog ref={dialogRef} onCancel={()=>{setSelected(null);setPolicy("");}} onClose={()=>{setSelected(null);setPolicy("");}}><div className="dialog-heading"><span className="eyebrow">{selected?"STUDENT CONTEXT":"WORKSPACE POLICY"}</span><button className="outline" onClick={()=>{setSelected(null);setPolicy("");}}>Close</button></div>{selected?<><h2>{selected.id}</h2><p>{selected.course}</p><div className="detail-score"><span className="tiny">RECONSTRUCTION ERROR</span><strong>{selected.error.toFixed(3)}</strong><span>{selected.error>threshold?"Above review threshold":"Within review threshold"} of {threshold.toFixed(3)}</span></div><dl><dt>Sessions</dt><dd>{selected.sessions}</dd><dt>Average minutes</dt><dd>{selected.minutes}</dd><dt>Completion</dt><dd>{selected.completion}%</dd></dl><h3>Suggested review</h3><p>Discuss study habits, access to course materials, and any support needs. Compare with course expectations before interpreting this score.</p><p className="policy-note">This interface reads supplied scores. It does not run the autoencoder or explain which feature caused a score.</p></>:<><h2>{policy}</h2>{policy==="Privacy Policy"?<><p>This demonstration processes imported CSV data in memory within your browser tab. The application code does not upload or persist those records. Reloading clears imported data.</p><p>Use pseudonymous student IDs and avoid personal or sensitive information. CSV exports contain the records in your current view and are saved to your device.</p><p>MagicPath and any eventual hosting provider may process normal connection and usage information under their own policies. A production deployment needs an operator-specific policy before collecting student data.</p></>:<><p>This demonstration is provided for research exploration. Supplied scores and an adjustable threshold produce a review queue; they do not establish misconduct, learning difficulty, or diagnosis.</p><p>You are responsible for permission to use imported data and for reviewing results in context. Do not use this demonstration as the sole basis for grading, disciplinary action, or other consequential decisions.</p><p>There is no account service, payment, model inference, or production availability commitment in this demonstration.</p></>}</>}</dialog>
 </div>;
};

