"use client";
import React,{useState,useRef,useEffect,useMemo,useDeferredValue} from "react";
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip} from "recharts";
import {FEATURE_KEYS,FEATURE_NAMES,SNAPSHOT,parseFeatures,summarize,filterRecords,exportFeatures,saveCSV,HEADER_ONLY_TEMPLATE,type FeatureRecord} from "../lib/features";
export const LearningObservatory=()=>{
 const [records,setRecords]=useState<FeatureRecord[]>([]),[fileName,setFileName]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState(""),[q,setQ]=useState(""),[tier,setTier]=useState("All tiers"),[category,setCategory]=useState("All labels"),[flagged,setFlagged]=useState(false),[feature,setFeature]=useState(3),[minimum,setMinimum]=useState(0),[sort,setSort]=useState("id"),[page,setPage]=useState(0),[chart,setChart]=useState("profile"),[selected,setSelected]=useState<FeatureRecord|null>(null),[policy,setPolicy]=useState(""),[motion,setMotion]=useState(true);
 useEffect(()=>{const preference=window.matchMedia("(prefers-reduced-motion: reduce)");const update=()=>setMotion(!preference.matches);update();preference.addEventListener("change",update);return ()=>preference.removeEventListener("change",update);},[]);
 const input=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null),root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const observer=new IntersectionObserver(items=>items.forEach(item=>{if(item.isIntersecting){item.target.classList.add("visible");observer.unobserve(item.target);}}),{threshold:.05});root.current?.querySelectorAll(".reveal").forEach(n=>observer.observe(n));return ()=>observer.disconnect();},[]);
 useEffect(()=>{if(selected||policy){if(!dialog.current?.open)dialog.current?.showModal();}else dialog.current?.close();},[selected,policy]);
 useEffect(()=>setPage(0),[q,tier,category,flagged,feature,minimum,sort,records]);
 const searchQuery=useDeferredValue(q);
 const loaded=records.length>0,totals=loaded?summarize(records):SNAPSHOT;
 const filtered=useMemo(()=>filterRecords(records,searchQuery,tier,category,flagged,feature,minimum).sort((a,b)=>sort==="score"?b.values[feature]-a.values[feature]:a.id.localeCompare(b.id)),[records,searchQuery,tier,category,flagged,feature,minimum,sort]);
 const shownSummary=loaded?summarize(filtered):SNAPSHOT;
 const categories=Array.from(new Set(records.map(r=>r.category))),tiers=Array.from(new Set(records.map(r=>r.tier)));
 const bars=chart==="profile"?FEATURE_NAMES.map((name,i)=>({name,value:Number(shownSummary.averages[i].toFixed(2))})):chart==="labels"?(loaded?Array.from(new Set(filtered.filter(r=>r.label===true).map(r=>r.category))).map(name=>({name,value:filtered.filter(r=>r.label===true&&r.category===name).length})):SNAPSHOT.labels.map(b=>({name:b.name,value:b.count}))):Array.from({length:10},(_,i)=>({name:i*10+"–"+(i*10+10),value:filtered.filter(r=>r.values[feature]>=i*10&&(i===9?r.values[feature]<=100:r.values[feature]<i*10+10)).length}));
 async function importCSV(event:React.ChangeEvent<HTMLInputElement>){const file=event.currentTarget.files?.[0],target=event.currentTarget;if(!file)return;setBusy(true);setStatus("");try{if(file.size>2_000_000)throw Error("Choose a CSV smaller than 2 MB.");const parsed=parseFeatures(await file.text());setRecords(parsed);setFileName(file.name);setQ("");setTier("All tiers");setCategory("All labels");setMinimum(0);setFlagged(false);setStatus("Loaded "+parsed.length.toLocaleString("en-US")+" students. "+parsed.filter(r=>r.label===true).length+" rows carry an anomaly label.");}catch(e){setStatus(e instanceof Error?e.message:"The file could not be read.");}finally{setBusy(false);target.value="";}}
 const openImport=()=>input.current?.click();
 const clear=()=>{setQ("");setTier("All tiers");setCategory("All labels");setFlagged(false);setMinimum(0);};
 const closeDialog=()=>{setSelected(null);setPolicy("");};
 return <div className={"edx "+(!motion?"still":"")} ref={root}><a className="skip" href="#explorer">Skip to dataset explorer</a>
 <header className="mast"><a href="#top" className="wordmark">edusentiel<span>STUDENT PATTERNS / HUMAN CONTEXT</span></a><nav aria-label="Main"><a href="#explorer">Explorer</a><a href="#method">Method</a><a href="#paper">Paper</a><button onClick={()=>setMotion(m=>!m)} aria-pressed={!motion}>{motion?"Pause motion":"Resume motion"}</button></nav><button className="solid small" onClick={openImport} disabled={busy}>{busy?"Reading file…":"Open your dataset"}</button></header>
 <input type="file" accept=".csv,text/csv" hidden ref={input} onChange={importCSV}/>
 <main id="top"><section className="hero"><div className="hero-label"><span>LEARNING BEHAVIOUR OBSERVATORY</span><span>RESEARCH EDITION / 01</span></div>
 <div className="hero-composition"><aside className="hero-stamp"><span>HOW LEARNING LEAVES A TRACE</span><strong>Small signals.<br/>A wider view.</strong><div className="stamp-rule"/><p>Attendance shows participation. Practice shows momentum. Scores and consistency help reveal how learning changes over time.</p><a href="#method" className="underlink">Understand the approach</a></aside>
 <h1><span>LEARNING</span><span className="headline-italic">IN CONTEXT.</span></h1><div className="hero-note"><span className="note-index">01 / READ THE SIGNAL</span><p>Spot a pattern.<br/>Ask a better question.</p><span>Dataset labels inform a review.<br/>People give the pattern meaning.</span></div></div>
 <div className="hero-bottom"><button className="solid" onClick={openImport} disabled={busy}>{busy?"Reading your dataset…":"Import features_df.csv"}</button><a href="#explorer" className="underlink">Explore the file snapshot</a><p>Import your original CSV directly.<br/>No six-column conversion needed.</p></div></section>
 <div className="ticker" aria-hidden="true"><div className="ticker-track">{[0,1].map(i=><span key={i}>OBSERVE / UNDERSTAND / SUPPORT / OBSERVE / UNDERSTAND / SUPPORT / </span>)}</div></div>
 <section className="cohort-section reveal"><div className="section-index">01 / THE COHORT</div><div className="cohort-layout"><h2>THE NUMBERS<br/><em>START THE<br/>CONVERSATION.</em></h2><div className="cohort-data"><div className="stat-line"><strong>{totals.count.toLocaleString("en-US")}</strong><div>Students in the dataset<span>{loaded?"Imported in this browser":"Verified from your attached file"}</span></div></div><div className="stat-line"><strong>{totals.flagged}</strong><div>Rows labelled as anomalies<span>{(totals.flagged/totals.count*100).toFixed(1)}% of this cohort • supplied labels</span></div></div><div className="context-copy">{loaded?<p>Filters below update the explorer. This cohort summary always shows the complete imported file.</p>:<p>This snapshot comes from your uploaded CSV. Import it to search students, inspect features, and export filtered records.</p>}</div></div></div></section>
 <section id="explorer" className="explorer reveal"><div className="explorer-head"><div><div className="section-index">02 / THE WORKING EXPLORER</div><h2>LOOK CLOSER.</h2></div><div className="source-label"><span className={loaded?"source-square loaded":"source-square"}/>{loaded?fileName:"Verified aggregate snapshot"}<span>{loaded?"LOCAL BROWSER SESSION":"IMPORT TO EXPLORE STUDENT ROWS"}</span></div></div>
 <div className="import-toolbar"><p>{loaded?records.length.toLocaleString("en-US")+" records loaded. Names, emails, and private identifiers are excluded from this view.":"Use your original features_df.csv with all 17 columns. Columns are matched by name, so their order can vary."}</p><button className="underlink" onClick={()=>saveCSV("edusentiel-native-schema.csv",HEADER_ONLY_TEMPLATE)}>Download matching schema</button></div>
 {status&&<div className="status-message" role="status">{status}<button onClick={()=>setStatus("")} aria-label="Dismiss import message">Dismiss</button></div>}
 <div className="explorer-controls"><label>SEARCH NAME, ROLL OR ID<input type="search" placeholder="Name, roll number or student ID" value={q} onChange={e=>setQ(e.target.value)} disabled={!loaded}/></label><label>CANDIDATE TIER<select value={tier} onChange={e=>setTier(e.target.value)} disabled={!loaded}><option>All tiers</option>{tiers.map(t=><option key={t}>{t}</option>)}</select></label><label>SUPPLIED LABEL<select value={category} onChange={e=>setCategory(e.target.value)} disabled={!loaded}><option>All labels</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="label-check"><input type="checkbox" checked={flagged} onChange={e=>setFlagged(e.target.checked)} disabled={!loaded}/>Anomaly-labelled only</label></div>
 <div className="feature-controls"><label>FEATURE IN FOCUS<select value={feature} onChange={e=>setFeature(Number(e.target.value))}>{FEATURE_NAMES.map((f,i)=><option key={f} value={i}>{f}</option>)}</select></label><label className="score-filter">MINIMUM FEATURE VALUE <output>{minimum}%</output><input aria-label="Minimum feature value" type="range" min="0" max="100" step="1" value={minimum} onChange={e=>setMinimum(Number(e.target.value))} disabled={!loaded}/></label><button className="outline" onClick={clear} disabled={!loaded}>Reset filters</button></div>
 <div className="visualisation"><div className="chart-title"><h3>{chart==="profile"?"THE LEARNING PROFILE":chart==="labels"?"SUPPLIED ANOMALY LABELS":FEATURE_NAMES[feature].toUpperCase()+" DISTRIBUTION"}</h3><span>{loaded?filtered.length.toLocaleString("en-US")+" FILTERED STUDENTS":"ACTUAL FILE AGGREGATES"}</span></div><div className="chart-tabs" role="group" aria-label="Chart views">{[["profile","Feature profile"],["labels","Label breakdown"],["distribution","Distribution"]].map(([v,label])=><button key={v} aria-pressed={chart===v} className={chart===v?"current":""} onClick={()=>setChart(v)} disabled={v==="distribution"&&!loaded}>{label}</button>)}</div>
 {busy?<div className="chart-skeleton" role="status" aria-label="Loading dataset"><span/><span/><span/><span/><span/><span/></div>:<div className="chart-box"><ResponsiveContainer width="100%" height={260}><BarChart data={bars} margin={{top:12,right:16,bottom:10,left:-15}}><XAxis dataKey="name" tickLine={false} axisLine={{stroke:"#697b64"}} tick={{fill:"#e7e3cd",fontSize:9}} interval={0}/><YAxis tickLine={false} axisLine={false} tick={{fill:"#c6cdb7",fontSize:10}} domain={chart==="profile"?[0,100]:[0,"auto"]}/><Tooltip cursor={false} contentStyle={{background:"#eee8d6",border:"1px solid #b7bd9f",borderRadius:0,boxShadow:"none",color:"#183a2d"}} formatter={value=>[value,chart==="profile"?"Average (%)":"Students"]}/><Bar dataKey="value" fill="#c8b678" isAnimationActive={motion} animationDuration={650} animationEasing="ease-out"/></BarChart></ResponsiveContainer></div>}
 <p className="chart-caption">{chart==="profile"?"Mean of each learning metric, on a 0 to 100 scale.":chart==="labels"?"Counts use the is_anomaly and anomaly_type columns already in your file.":"Number of students in each 10-point feature interval."} {loaded?"Charts reflect your current filters.":"Import the CSV to enable record-level exploration."}</p></div>
 <div className="register-heading"><div><h3>THE STUDENT REGISTER</h3><span>{loaded?filtered.length+" matches":"Waiting for your CSV"}</span></div><div><select aria-label="Sort students" value={sort} onChange={e=>setSort(e.target.value)} disabled={!loaded}><option value="id">Student ID</option><option value="score">Highest feature value</option></select><button className="outline" disabled={!loaded||!filtered.length} onClick={()=>saveCSV("edusentiel-filtered-records.csv",exportFeatures(filtered))}>Export view</button></div></div>
 {!loaded?<div className="import-empty"><span>YOUR DATA, YOUR CONTEXT.</span><h3>Bring the cohort into focus.</h3><p>Import features_df.csv to activate the register. Your file is processed in this browser tab.</p><button className="solid" onClick={openImport}>Import your dataset</button></div>:<><div className="table-scroll"><table><thead><tr><th>STUDENT</th><th>ROLL NUMBER</th><th>{FEATURE_NAMES[feature].toUpperCase()}</th><th>PROBLEMS SOLVED</th><th>INACTIVE WEEKS</th><th>DATASET LABEL</th><th>TIER</th><th><span className="sr-only">Student details</span></th></tr></thead><tbody>{filtered.slice(page*10,page*10+10).map(r=><tr key={r.id}><td><strong className="student-name">{r.name||r.id}</strong>{r.name&&<span className="student-id">{r.id}</span>}</td><td>{r.roll||"Not supplied"}</td><td><div className="value-cell"><span>{r.values[feature].toFixed(2)}%</span><span className="mini-track"><span style={{width:r.values[feature]+"%"}}/></span></div></td><td>{r.problems??"Not supplied"}</td><td>{r.inactive??"Not supplied"}</td><td><span className={r.label===true?"dataset-badge flagged":"dataset-badge"}>{r.category}</span></td><td>{r.tier}</td><td><button className="underlink" onClick={()=>setSelected(r)}>Inspect</button></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="no-results"><h3>No records match these filters.</h3><button className="outline" onClick={clear}>Reset filters</button></div>}<div className="pagination"><span>{filtered.length?Math.min(page*10+1,filtered.length):0}–{Math.min(page*10+10,filtered.length)} of {filtered.length}</span><div><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={(page+1)*10>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></>}
 </section>
 <section id="method" className="method-section reveal"><div className="section-index">03 / THE METHOD</div><div className="method-layout"><h2>EVERY SIGNAL<br/>NEEDS <em>CONTEXT.</em></h2><div className="method-questions"><details open><summary>01 / What am I looking at?</summary><p>Six learning metrics and the labels already provided in your dataset. The explorer helps you compare activity, scores, and consistency within a cohort.</p></details><details><summary>02 / Are these model predictions?</summary><p>No. The file contains no reconstruction-error values. This version reads supplied anomaly labels and does not train or run an autoencoder. Labels are shown as dataset annotations.</p></details><details><summary>03 / How is my CSV handled?</summary><p>The file is parsed in memory in your browser tab. The interface does not transmit or store its rows. Names and roll numbers stay in memory only to support search. Emails and candidate IDs are discarded. Exports omit names and roll numbers.</p></details><details><summary>04 / What should happen after a flag?</summary><p>Review course expectations and access needs. Talk with the student. A supplied label is an invitation to investigate and is insufficient for grading or disciplinary decisions.</p></details></div></div></section>
 <section id="paper" className="paper-section reveal" aria-labelledby="paper-title"><div className="section-index">04 / THE RESEARCH PAPER</div><div className="paper-layout"><h2 id="paper-title">READ THE<br/><em>RESEARCH.</em></h2><div className="paper-copy"><p>Explore the research behind abnormal learning behaviour detection. Download the project paper to read it offline.</p><a className="solid paper-download" href="/api/paper" download="Edusentiel-Research-Paper.pdf">Download paper (PDF)</a><a className="underlink" href="/paper" target="_blank" rel="noopener noreferrer">Read paper in a new tab</a><span className="small-note">PDF / 339 KB</span></div></div></section>
 <section className="closing reveal"><span>OBSERVE / UNDERSTAND / SUPPORT</span><h2>KEEP THE<br/><em>HUMAN IN VIEW.</em></h2><button className="solid" onClick={openImport}>Open your dataset</button></section></main>
 <footer><a className="wordmark" href="#top">edusentiel</a><span>LEARNING INTELLIGENCE / RESEARCH EDITION</span><div><button onClick={()=>setPolicy("Privacy Policy")}>Privacy Policy</button><button onClick={()=>setPolicy("Terms of Service")}>Terms of Service</button></div></footer>
 <dialog ref={dialog} aria-labelledby="dialog-title" onCancel={closeDialog} onClose={closeDialog}><div className="dialog-top"><span>{selected?"STUDENT CONTEXT":"WORKSPACE POLICY"}</span><button className="outline" onClick={closeDialog}>Close</button></div>{selected?<><h2 id="dialog-title">{selected.name||selected.id}</h2><p className="small-note">Student ID: {selected.id} / Roll: {selected.roll||"Not supplied"}</p><p className="dialog-label">{selected.tier} / {selected.category}</p><p className="small-note">Label supplied in the dataset. No model prediction is made here.</p><div className="detail-features">{FEATURE_NAMES.map((name,i)=><div key={name}><span>{name}</span><strong>{selected.values[i].toFixed(2)}%</strong><div className="detail-track"><span style={{width:selected.values[i]+"%"}}/></div></div>)}</div><dl><dt>Practice problems solved</dt><dd>{selected.problems??"Not supplied"}</dd><dt>Zero activity weeks</dt><dd>{selected.inactive??"Not supplied"}</dd><dt>Supplied severity</dt><dd>{selected.severity}</dd></dl><p>Interpret these values alongside the student's course, study habits, and access needs.</p></>:<><h2 id="dialog-title">{policy}</h2>{policy==="Privacy Policy"?<><p>Imported CSV rows are processed in memory within this browser tab. This interface does not upload those rows or save them in browser storage. Reloading clears the imported cohort.</p><p>Names, roll numbers, student IDs, metrics, and supplied labels stay in memory for this session. Emails and candidate IDs are discarded. Names and roll numbers are omitted from exports. Filtered exports are downloaded to your device.</p><p>The initial view contains aggregate statistics from the attached dataset, without student records. MagicPath and any hosting provider may process normal connection information under their own policies.</p></>:<><p>This research interface displays learning metrics and annotations supplied by a CSV. It does not establish misconduct, learning difficulty, or diagnosis, and it does not run the autoencoder.</p><p>You are responsible for permission to use imported data. Review results in context; do not use a label alone to make grading, disciplinary, or other consequential decisions.</p><p>This demonstration has no payment service, account service, or production availability commitment.</p></>}</>}</dialog>
 </div>;
};
